version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3000:3000"
    volumes:
      - uploads_data:/usr/src/app/uploads
    environment:
      - NODE_ENV=production
    command: npm start

volumes:
  uploads_data:
