services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - uploads_data:/usr/src/app/uploads
    environment:
      - NODE_ENV=development
    command: npm start

volumes:
  uploads_data:
